@startuml UC_Conteudo
left to right direction
skinparam PackageStyle rectangle

actor "Usuário" as U

rectangle "Sistema de Escrita Criativa - Gestão Criativa" {
    package "Conteúdo" {
        usecase "UC01: Criar novo projeto" as UC01
        usecase "UC02: Editar dados do projeto" as UC02
        usecase "UC03: Criar personagem" as UC03
        usecase "UC04: Editar dados do personagem" as UC04
        usecase "UC05: Upload de imagem" as UC05
        usecase "UC06: Criar nota de texto" as UC06
        usecase "UC09: Exclusão de entidades e itens do projeto" as UC09
    }
}

U --> UC01
U --> UC02
U --> UC03
U --> UC04
U --> UC05
U --> UC06
U --> UC09

UC03 .> UC05: <<include>>
UC04 .> UC05: <<include>>
UC06 .> UC05: <<include>>
@enduml
