@startuml Diagrama01
left to right direction
skinparam PackageStyle rectangle

actor "Usuario" as U

rectangle "Sistema de Escrita Criativa - Gestão Criativa" {
    package "Diagramação" {
        usecase "UC02: Criar Diagrama de Relacionamento de Entidades" as UC02
        usecase "UC07: Gestão de Grupos de Nós em Diagramas" as UC07
        usecase "UC11: Excluir Nó e Tratar Arestas Órfãs" as UC11
        usecase "UC13: Gestão de Atributos Detalhados no Diagrama" as UC13
    }

    package "Conteúdo" {
        usecase "UC01: Criar Novo Projeto" as UC01
        usecase "UC08: Upload e Compressão de Imagens de Personagens" as UC08
        usecase "UC09: Criação e Categorização de Ideias" as UC09
        usecase "UC18: Consultar Histórico Temporal de Personagem ou Projeto" as UC18
        usecase "UC15: Exclusão de Entidades e Itens do Projeto" as UC15
    }
}

U --> UC01
U --> UC02
U --> UC07
U --> UC08
U --> UC09
U --> UC11
U --> UC13
U --> UC15
U --> UC18

UC01 <.-. UC09: <<extends>>
UC01 <.-. UC15: <<extends>>

UC02 <.-. UC13: <<extends>>
@enduml
