@startuml Diagrama02
left to right direction

actor "Usuário"as U

rectangle "Sistema de Escrita Criativa - Organização" {
    usecase "UC04: Organizar Elementos via Drag-and-Drop" as UC04
    usecase "UC05: Busca Global com Filtros e Tags" as UC05
    usecase "UC12: Exclusão de Pastas e Conteúdo" as UC12
}

U --> UC04
U --> UC05
U --> UC12
@enduml
