@startuml diagrama_UC04

|Usuário|
start
:Acessar lista de personagens;
:Selecionar personagem;
:Alterar dados da ficha;
if (Deseja atualizar imagem?) then (sim)
  :Acionar upload de imagem;
endif
if (Deseja remover imagem atual?) then (sim)
  :Remover imagem do perfil;
endif
:Clicar em "Salvar";

|Sistema|
:Persistir alterações da ficha;
:Atualizar listagem;

stop
@enduml
