@startuml diagrama_UC18

|Usuário|
start
:Acessar "Configurações Gerais";
:Selecionar "Definir senha de acesso";
:Inserir nova senha;
:Confirmar nova senha;

|Sistema|
if (Senha e confirmação iguais?) then (sim)
  if (Senha atende política mínima?) then (sim)
    :Salvar senha de acesso;
  else (não)
    :Exibir regra de senha inválida;
    stop
  endif
else (não)
  :Exibir erro de confirmação;
  stop
endif

|Usuário|
:Reiniciar aplicativo;

|Sistema|
repeat
  :Solicitar senha;
  |Usuário|
  :Inserir senha;
  |Sistema|
repeat while (Senha válida?) is (não)
:Permitir acesso à tela inicial;

stop
@enduml
