@startuml diagrama_UC10

|Usuário|
start
:Acessar listagem de itens;
:Selecionar configurações da pasta;
if (Deseja renomear?) then (sim)
  :Informar novo nome;
endif
:Selecionar "Excluir pasta";

|Sistema|
:Solicitar tipo de exclusão;

|Usuário|
if (Deseja excluir conteúdo?) then (Apenas pasta)
  |Sistema|
  :Mover itens para o diretório raiz;
  :Excluir pasta vazia;
else (Pasta e conteúdo)
  |Sistema|
  :Confirmar ação irreversível;
  :Remover pasta e subitens;
endif

:Atualizar estrutura de diretórios;
stop
@enduml
