@startuml diagrama_UC04

|Usuário|
start
:Acessar lista de personagens;
:Selecionar personagem;
:Alterar dados da ficha;
if (Deseja atualizar imagem?) then (sim)
  :Acionar upload de imagem;
endif
:Clicar em "Salvar";

|Sistema|
if (Dados válidos?) then (sim)
  :Persistir alterações da ficha;
else (não)
  :Exibir inconsistências de validação;
endif

stop
@enduml
