@startuml diagrama_UC20

|Usuário|
start
if (Deseja visualização rápida?) then (sim)
  |Sistema|
  :Exibir descrição sem abrir editor completo;
  stop
endif

|Usuário|
:Selecionar aresta e abrir edição;
:Inserir descrição da relação;

|Sistema|
:Salvar metadados da aresta;

|Usuário|
:Selecionar nó e abrir edição;
:Inserir descrição do nó;

|Sistema|
:Salvar metadados do nó;
:Exibir indicador visual de descrição;

stop
@enduml
