@startuml diagrama_UC06

|Usuário|
start
:Acessar tela de listagem de notas;
:Criar nova nota;
:Informar título (opcional);
:Escrever conteúdo;
:Adicionar tags (opcional);
if (Deseja adicionar imagem?) then (sim)
  :Acionar UC05 (Upload de imagem);
endif
:Clicar em "Salvar";

|Sistema|
if (Título informado?) then (sim)
  :Persistir nota com conteúdo e tags;
else (não)
  :Definir título como "Sem título";
  :Persistir nota com conteúdo e tags;
endif
:Atualizar listagem de notas;

stop
@enduml
