@startuml diagrama_UC06

|Usuário|
start
:Acessar tela de listagem de notas;
:Criar nova nota e inserir título;
fork
  :Escrever texto em Markdown;
fork again
  :Adicionar tags;

  if (Deseja adicionar imagem?) then (sim)
    |Usuário|
    :Escolher câmera ou galeria;
    |Sistema|
    :Capturar arquivo;
    if (Tamanho respeita RNF05?) then (sim)
      :Associar imagem à nota;
    else (não)
      :Bloquear e exibir erro;
    endif
  endif
end fork

|Usuário|
:Clicar em "Salvar";
|Sistema|
:Persistir nota com conteúdo e tags;

stop
@enduml
