@startuml diagrama_UC09

|Usuário|
start
if (Deseja facilitar busca?) then (sim)
  :Utilizar ordenação/filtro;
endif
:Localizar item (Nota, Personagem ou Diagrama);
:Clicar em "Excluir";

|Sistema|
:Exibir alerta de confirmação irreversível;

|Usuário|
if (Confirma exclusão?) then (sim)
  |Sistema|
  :Remover registro do banco de dados;
  :Liberar memória;
  :Atualizar interface;
else (não)
  |Sistema|
  :Cancelar exclusão;
endif

stop
@enduml
