@startuml diagrama_UC01

|Sistema|
start
:Exibir tela inicial;
:Carregar projetos recentes;

|Usuário|
:Clicar em "Novo Projeto";
:Informar nome do projeto;
:Confirmar criação;

|Sistema|
if (Nome informado?) then (sim)
  :Criar projeto;
  :Criar pasta raiz do projeto na área de notas;
else (não)
  :Exibir validação de nome obrigatório;
endif

stop
@enduml
