@startuml diagrama_UC05

|Usuário|
start
:Clicar na área de imagem do item;
:Selecionar origem (câmera/galeria);
:Selecionar arquivo;

|Sistema|
if (Arquivo maior que 5MB?) then (sim)
  :Exibir mensagem de erro;
  stop
else (não)
  :Validar formato da imagem;
  :Salvar imagem no item em edição;
  :Exibir pré-visualização;
endif

|Usuário|
:Confirmar salvamento;
stop
@enduml
