@startuml diagrama_UC02

|Usuário|
start
:Acessa a seção "Diagramas";
:Seleciona "Criar novo Diagrama";

|Sistema|
:Abre o plano de edição de diagramas;

if (Composição do diagrama correta?) then (sim)
    |Usuário|
    :Insere dois nós e os conecta através de uma aresta;
    :Aciona o botão "Salvar";
    
    |Sistema|
    :Valida as regras de estrutura mínima do diagrama;
    :Persiste os dados do diagrama;
else (não)
    |Usuário|
    :Tenta salvar o diagrama com menos de dois nós ou sem arestas;
    :Recebe uma mensagem de erro;

    |Sistema|
    :Exibe alerta;
    :Bloqueia a persistência;
endif

stop
@enduml