@startuml diagrama_UC11

|Usuário|
start
:Acessar "Configurações Gerais";

|Sistema|
:Apresentar opções disponíveis;

|Usuário|
:Selecionar configuração desejada;
:Alterar preferência;

|Sistema|
:Aplicar alteração;

|Sistema|
:Salvar preferências;
stop
@enduml
