@startuml diagrama_UC16

|Usuário|
start
:Selecionar múltiplos nós no editor;
:Acionar "Criar grupo de nós";
:Definir nome e cor;

|Sistema|
:Criar grupo;

|Usuário|
if (Deseja ajustar o grupo?) then (sim)
  if (Ação escolhida?) then (Remover nó)
  :Selecionar nó e acionar "Remover do grupo";
  |Sistema|
  :Manter nó independente no diagrama;
  else (Excluir grupo)
  :Selecionar grupo e acionar "Excluir grupo";
    |Sistema|
    :Remover grupo e manter nós no diagrama;
  endif
endif

stop
@enduml
