@startuml diagrama_UC07

|Usuário|
start
:Acessar listagem de itens;
:Clicar em "Criar pasta";
:Informar nome da pasta;
if (Deseja cancelar criação?) then (sim)
  :Encerrar ação sem criar pasta;
  stop
endif
:Confirmar criação;

|Sistema|
if (Possui nome?) then (sim)
  :Criar pasta na estrutura atual;
  :Atualizar listagem;
else (não)
  :Exibir mensagem de nome vazio;
endif

stop
@enduml
