@startuml diagrama_UC04

|Usuário|
start
:Pressiona e segura um item (nó ou arquivo);

if (Cancelamento de movimento?) then (sim)
    |Usuário|
    :Arrasta o item para uma área inválida;
    
    |Sistema|
    :Retorna o item à posição original;
else (não)
    |Usuário|
    :Arrasta o item para uma nova coordenada ou para cima de uma pasta;

    |Sistema|
    :Fornece feedback visual imediato durante o movimento;
    
    |Usuário|
    :Solta o item;

    |Sistema|
    :Valida a nova posição;
    :Confirma a alteração de posição;
endif

stop
@enduml