@startuml diagrama_UC02

|Usuário|
start
:Acessar tela de edição do projeto;
:Alterar nome e/ou sinopse;
:Ajustar cor/tags/personagens do cartão;
if (Deseja atualizar imagem?) then (sim)
  :Acionar upload de imagem;
endif
if (Deseja remover imagem atual?) then (sim)
  :Remover imagem do cartão;
endif
:Clicar em "Salvar";

|Sistema|
:Persistir alterações do projeto;
:Exibir confirmação de sucesso;

stop
@enduml
