@startuml diagrama_UC01

|Sistema|
start
:Abre a tela inicial;

|Usuário|
:Clica no botão "Novo Projeto";

|Sistema|
:Cria um novo projeto;
:Registra automaticamente a data de criação do projeto;

'Será analisado a necessidade de utilizar "Sistema" como ator
stop
@enduml
